"""add_greetings_and_whatsapp_number

Revision ID: 269329a6ef2b
Revises: 78db233c9903
Create Date: 2025-08-04 10:57:10.347314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '269329a6ef2b'
down_revision: Union[str, Sequence[str], None] = '78db233c9903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # בדיקה אם האינדקסים והטבלאות כבר קיימות
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    # ### commands auto generated by Alembic - please adjust! ###
    # לא נמחק את הטבלאות - הן נחוצות
    # אם יש אינדקסים, נמחק רק אותם (אם קיימים)
    if 'greetings' in tables:
        indexes_greetings = [idx['name'] for idx in inspector.get_indexes('greetings')]
        if 'ix_greetings_id' in indexes_greetings:
            op.drop_index(op.f('ix_greetings_id'), table_name='greetings')
    
    if 'audit_log' in tables:
        indexes_audit = [idx['name'] for idx in inspector.get_indexes('audit_log')]
        if 'ix_audit_log_id' in indexes_audit:
            op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('greetings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('signer_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('greetings_event_id_fkey')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('greetings_guest_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('greetings_pkey'))
    )
    op.create_index(op.f('ix_greetings_id'), 'greetings', ['id'], unique=False)
    # ### end Alembic commands ###
