"""add table_head_id to guests

Revision ID: 39fff4f1bfb4
Revises: 64cb3fe12e87
Create Date: 2025-07-15 13:42:23.667183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fff4f1bfb4'
down_revision: Union[str, Sequence[str], None] = '64cb3fe12e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('table_head_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guests', 'table_heads', ['table_head_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guests', type_='foreignkey')
    op.drop_column('guests', 'table_head_id')
    # ### end Alembic commands ###
