"""add x and y to tables

Revision ID: 03bee4af409a
Revises: ab6d40372fff
Create Date: 2025-07-13 15:31:00.900899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bee4af409a'
down_revision: Union[str, Sequence[str], None] = 'ab6d40372fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('x', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'y')
    op.drop_column('tables', 'x')
    # ### end Alembic commands ###
