"""add admin_id to Event

Revision ID: 2b20dd9ce5cd
Revises: 3e2a4a6b5dd3
Create Date: 2025-07-08 16:29:01.164778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b20dd9ce5cd'
down_revision: Union[str, Sequence[str], None] = '3e2a4a6b5dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'admin_id')
    # ### end Alembic commands ###
