"""add gender to guests

Revision ID: 4ca9f700798b
Revises: b864e5bba835
Create Date: 2025-07-24 11:20:27.807882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca9f700798b'
down_revision: Union[str, Sequence[str], None] = 'b864e5bba835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('gender', sa.String(), nullable=True))
    op.alter_column('tables', 'hall_type',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'hall_type',
               existing_type=sa.String(),
               nullable=True)
    op.drop_column('guests', 'gender')
    # ### end Alembic commands ###
