"""Make id_number nullable

Revision ID: ab6d40372fff
Revises: b237baab5a56
Create Date: 2025-07-09 16:01:08.392064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6d40372fff'
down_revision: Union[str, Sequence[str], None] = 'b237baab5a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'id_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'id_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('users_id_number_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_id_number_key'), 'users', ['id_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'id_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('guests', 'id_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
